# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halfwayapp', '0005_auto_20160224_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='starting_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halfwayapp.Address'),
        ),
    ]
