# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halfwayapp', '0008_auto_20160225_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='halfwayapp.Address'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participant_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Participant_two', to='halfwayapp.Participant'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='trip_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='starting_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='halfwayapp.Address'),
        ),
    ]
