# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halfwayapp', '0009_auto_20160225_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='trip_id',
        ),
    ]
