# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halfwayapp', '0010_remove_meeting_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='starting_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='halfwayapp.Address'),
        ),
    ]
