# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halfwayapp', '0014_auto_20160225_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participant_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_one', to='halfwayapp.Participant'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participant_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_two', to='halfwayapp.Participant'),
        ),
    ]
