# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halfwayapp', '0015_auto_20160225_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='business_type',
            field=models.TextField(blank=True, choices=[(b'Coffee', b'Coffee Shop'), (b'Bar', b'Bar'), (b'Eatery', b'Restaurant')], null=True),
        ),
    ]
