# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halfwayapp', '0017_auto_20160226_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='trip_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
