# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halfwayapp', '0018_meeting_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='trip_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
